domains:
- domain: ifconfig.cloud
  type: PRIMARY
  zone: ifconfig.cloud
name: ifconfig-cloud
region: nyc
services:
- http_port: 8000
  image:
    registry: mota
    registry_type: DOCKER_HUB
    repository: ifconfig
    tag: latest
  instance_count: 1
  instance_size_slug: basic-xxs
  name: ifconfig-cloud
  routes:
  - path: /
  source_dir: /
