domains:
- domain: ifconfig.cloud
  type: PRIMARY
  zone: ifconfig.cloud
envs:
- key: NEWRELIC_CONFIG_LICENSE
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:irv+8JpvfGNu4gTJ+m+WPzYbZzgAlvyB:Hbmq5DgLvV8OmsMZ73I1wCWvZWeB6AY4F4dNdyy5o7gRVu2BIVR2NrkBLdhhKEq4dnteTn4ubTs=]
- key: NEWRELIC_APP_NAME
  scope: RUN_AND_BUILD_TIME
  value: ifconfig.cloud
name: ifconfig-cloud
region: nyc
services:
- http_port: 8000
  image:
    registry: mota
    registry_type: DOCKER_HUB
    repository: ifconfig
    tag: latest
  instance_count: 1
  instance_size_slug: basic-xxs
  name: ifconfig-cloud
  run_command: "go run . -use-newrelic"
  routes:
  - path: /
  source_dir: /
